# Базовые настройки для Relocation Service
server:
  port: 0

spring:
  application:
    name: RELOCATION-SERVICE
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/relocation-db}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  liquibase:
    change-log: db.changelog/changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  main:
    banner-mode: "off"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - retry
          - env
          - circuitbreakers
          - circuitbreakerevents

logging:
  level:
    root: info
    by.javaguru.jdmk15.relocationservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: DEBUG

  file:
    name: logs/relocation-service.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      accounting-service:
        sliding-window-type: COUNT_BASED # Тип окна статистики: # COUNT_BASED — анализируется последние N вызовов
        # (альтернатива: TIME_BASED — за период времени)
        sliding-window-size: 4 # Сколько последних вызовов учитывать для расчёта процента ошибок
        minimum-number-of-calls: 4 # Минимальное количество вызовов перед тем как circuit breaker начнёт анализировать ошибки# (чтобы не открывался слишком рано на малом количестве запросов)
        failure-rate-threshold: 50 # Процент неуспешных вызовов, после которого circuit breaker откроется(здесь: если >= 50% из последних 4 вызовов — ошибка)
        wait-duration-in-open-state: 60s # Сколько времени circuit breaker будет находиться в состоянии OPEN(все запросы сразу будут отклоняться без попытки вызова сервиса)
        permitted-number-of-calls-in-half-open-state: 3 # Сколько пробных вызовов разрешено в состоянии HALF_OPEN(чтобы проверить — сервис восстановился или нет)
        automatic-transition-from-open-to-half-open-enabled: true #Автоматически переводит circuit breaker из OPEN в HALF_OPEN. после wait-duration-in-open-state
        record-exceptions:
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityTechnicalException
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - feign.RetryableException
        ignore-exceptions:
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityFunctionalException
      security-service:
        sliding-window-type: COUNT_BASED # Тип окна статистики: # COUNT_BASED — анализируется последние N вызовов
        # (альтернатива: TIME_BASED — за период времени)
        sliding-window-size: 4 # Сколько последних вызовов учитывать для расчёта процента ошибок
        minimum-number-of-calls: 4 # Минимальное количество вызовов перед тем как circuit breaker начнёт анализировать ошибки# (чтобы не открывался слишком рано на малом количестве запросов)
        failure-rate-threshold: 50 # Процент неуспешных вызовов, после которого circuit breaker откроется(здесь: если >= 50% из последних 4 вызовов — ошибка)
        wait-duration-in-open-state: 60s # Сколько времени circuit breaker будет находиться в состоянии OPEN(все запросы сразу будут отклоняться без попытки вызова сервиса)
        permitted-number-of-calls-in-half-open-state: 3 # Сколько пробных вызовов разрешено в состоянии HALF_OPEN(чтобы проверить — сервис восстановился или нет)
        automatic-transition-from-open-to-half-open-enabled: true #Автоматически переводит circuit breaker из OPEN в HALF_OPEN. после wait-duration-in-open-state
        record-exceptions:
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityTechnicalException
          - feign.FeignException.InternalServerError
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - feign.RetryableException
        ignore-exceptions:
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityFunctionalException
  retry:
    retry-aspect-order: 2
    instances:
      accounting-service:
        max-attempts: 3                  # Сколько всего попыток выполнить вызов (1 основной + 2 повтора)
        wait-duration: 300ms            # Пауза между попытками ретрая
        enable-exponential-backoff: true # Включает экспоненциальную задержку между ретраями
        exponential-backoff-multiplier: 2 # Во сколько раз увеличивается задержка после каждой попытки
        retry-exceptions:
          - feign.RetryableException      # Сетевые ошибки Feign (обычно timeout, connection refused и т.п.)
          - java.net.SocketTimeoutException # Таймауты при соединении
          - java.io.IOException           # Проблемы сети/ввода-вывода
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityTechnicalException
        # При этих исключениях будет выполняться повтор запроса
        ignore-exceptions:
          - feign.FeignException.BadRequest   # 400 — ошибка запроса (ретраить бессмысленно)
          - feign.FeignException.Unauthorized # 401 — не авторизован
          - feign.FeignException.Forbidden    # 403 — доступ запрещён
          - feign.FeignException.NotFound     # 404 — ресурс не найден
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityFunctionalException
        # Эти ошибки считаются бизнес/клиентскими и НЕ должны ретраиться
      security-service:
        max-attempts: 3                  # Сколько всего попыток выполнить вызов (1 основной + 2 повтора)
        wait-duration: 300ms            # Пауза между попытками ретрая
        enable-exponential-backoff: true # Включает экспоненциальную задержку между ретраями
        exponential-backoff-multiplier: 2 # Во сколько раз увеличивается задержка после каждой попытки
        retry-exceptions:
          - feign.RetryableException      # Сетевые ошибки Feign (обычно timeout, connection refused и т.п.)
          - java.net.SocketTimeoutException # Таймауты при соединении
          - java.io.IOException           # Проблемы сети/ввода-вывода
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityTechnicalException
        # При этих исключениях будет выполняться повтор запроса
        ignore-exceptions:
          - feign.FeignException.BadRequest   # 400 — ошибка запроса (ретраить бессмысленно)
          - feign.FeignException.Unauthorized # 401 — не авторизован
          - feign.FeignException.Forbidden    # 403 — доступ запрещён
          - feign.FeignException.NotFound     # 404 — ресурс не найден
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
          - by.javaguru.jdmk15.relocationservice.api.exception.SecurityFunctionalException
        # Эти ошибки считаются бизнес/клиентскими и НЕ должны ретраиться
